dataset: 
  name: "SplitMNIST"
  n_tasks: 5
  eval_ratio: 0.2
  test_ratio: 0.2
  seed: 42

model:
  type: "SimpleMLP"
  input_dim: 784
  hidden_dims: 128
  output_dim: 10
  optimizer: "SGD"
  lr: 0.01
  dropout: 0.5
  criterion: "CrossEntropyLoss"
  epochs: 2
  batch: 128

strategies:
  # - name: "HillClimbing"
  #   n_calls: 50
  #   params: {
  #     restart: 3
  #   } 
  - name: "RandomSearch"
    n_calls: 50
    params: {}
  # - name: "Genetic"
  #   n_calls: 10
  #   params: {
  #     population: 600,
  #     cross: "one point",
  #     mutation_rate: 0.1,
  #     elite_size: 50,
  #     tournament_size: 5
    # }
      

