dataset:
  eval_ratio: 0.2
  n_tasks: 5
  name: SplitMNIST
  seed: 42
  test_ratio: 0.2
model:
  batch: 128
  criterion: CrossEntropyLoss
  dropout: 0.5
  epochs: 4
  hidden_dims: 128
  input_dim: 784
  lr: 0.01
  optimizer: SGD
  output_dim: 10
  type: SimpleMLP


strategies:
  - class_name: "HillClimbingStart"
    name: "HillClimbingStart swaps 1"
    buffer_size: 500
    n_calls: 500
    params: {
      swaps: 1
    }
  - class_name: "HillClimbingStart"
    name: "HillClimbingStart swaps 10"
    buffer_size: 500
    n_calls: 500
    params: {
      swaps: 10
    }
  - class_name: "HillClimbingStart"
    name: "HillClimbingStart swaps 50"
    buffer_size: 500
    n_calls: 50
    params: {
      swaps: 50
    }
  # - name: "RandomSearch"
  #   buffer_size: 500
  #   n_calls: 6
  #   params: {}
  # - name: "Genetic"
  #   buffer_size: 500
  #   n_calls: 6
  #   params: {
  #     epochs: 20,
  #     population: 3,
  #     mutation_rate: 0.5,
  #     reproduce_rate: 0,
  #     elite_size: 2,
  #     tournament_size: 2
  #   }
  # - name: "PBIL"
  #   buffer_size: 500
  #   n_calls: 5
  #   params: {
  #     epochs: 20,
  #     population: 3,
  #     learning_rate: 0.1,
  #     mutation_prob: 0.05,
  #     mutation_shift: 0.05,
  #   }
