dataset: 
  name: "SplitCIFAR10"
  n_tasks: 5
  eval_ratio: 0.2
  test_ratio: 0.2
  seed: 42

model:
  type: "SimpleMLP"
  input_dim: 3072
  hidden_dims: 512
  output_dim: 10
  optimizer: "SGD"
  lr: 0.01
  dropout: 0.5
  criterion: "CrossEntropyLoss"
  epochs: 5
  batch: 512

strategies:
  - name: "HillClimbing"
    buffer_size: 500
    n_calls: 50
    params: {
      restart: 1
    } 
  # - name: "RandomSearch"
  #   buffer_size: 500
  #   n_calls: 100
  #   params: {}
  - name: "Genetic"
    buffer_size: 500
    n_calls: 50
    params: {
      epochs: 20,
      population: 40,
      mutation_rate: 0.1,
      reproduce_rate: 0.9,
      elite_size: 2,
      tournament_size: 2
    }
  - name: "PBIL"
    buffer_size: 500
    n_calls: 6
    params: {
      epochs: 20,
      population: 2,
      learning_rate: 0.1,
      mutation_prob: 0.05
    }
