[project]
name = "continual-buffer-optimization"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "avalanche-lib>=0.6.0",
    "black>=25.12.0",
    "isort>=7.0.0",
    "mypy>=1.19.1",
    "pytest>=9.0.2",
    "ruff>=0.14.10",
    "types-pyyaml>=6.0.12.20250915",
]

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = [
  "avalanche.*",
  "torch.*",
  "torchvision.*"
]
ignore_missing_imports = true
